import type { Metadata } from "next";
import { IBM_Plex_Sans, Lilex } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/cn";

const sans = IBM_Plex_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const mono = Lilex({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "James Blair",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", sans.variable, mono.variable)}
    >
      <body className="min-h-full flex flex-col leading-relaxed font-sans">
        {children}
      </body>
    </html>
  );
}
